apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
  namespace: egs-uniride
spec:
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
        - name: notifications-api
          image: registry.deti:5000/egs-uniride/notifications-api:0003
          ports:
            - containerPort: 8010
---
apiVersion: v1
kind: Service
metadata:
  name: notificationsapi-svc
  namespace: egs-uniride
spec:
  ports:
    - protocol: TCP
      port: 8010
      name: notifapi-svc-port
      
  selector:
    app: notifications-api

  type: ClusterIP